### PR TITLE
Fix Magnet pulling fake item entities

### LINKED ISSUE #15595: Item Dislocator dislocates visual-only items inside Molecular Assemblers
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

The Item Dislocator (Draconic Evolution) has no effect on purely visual item representations in the world

### The Reality

The Item Dislocator dislocates AE2's Molecular Assembler's "crafted item" preview out of the machine and to the player's feet.

I have only tested this as a client connected to a dedicated server.

### Your Proposal

Add some form of exclusion logic to prevent the visual-only items from being dislocated/magneted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Ruling-0**
Magnet will ignore the special EntityItem AE2 uses for rendering such as within the Molecular Assembler.

fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15595

image

### CODE REVIEW

File: src/main/java/com/brandon3055/draconicevolution/common/items/tools/Magnet.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public void onUpdate(ItemStack stack, World world, Entity entity, int slot, bool
             boolean playSound = false;
 
             for (EntityItem item : items) {
-                if (item.getEntityItem() == null) {
+                if (item.getEntityItem() == null || item.delayBeforeCanPickup < 0) {
```
Comment (serenibyss) [inline src/main/java/com/brandon3055/draconicevolution/common/items/tools/Magnet.java]: This solution is too much of a hack, I would rather just add the dependency and a check behind a cached `isModLoaded()` call than do something like this

Comment (Ruling-0) [reply src/main/java/com/brandon3055/draconicevolution/common/items/tools/Magnet.java]: Now does checking similar to other parts of the mod.

**Review by serenibyss — APPROVED** [review]

**Comment by boubou19** [comment]
a 8+ year annoyance that is now gone. Thank you.
