### PR TITLE
Fix Draconic Armor offhand rendering

### LINKED ISSUE #23301: Draconic Chest Model doesn't work well with offhand
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.8.4

### Your Server

sp

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Render the arms properly

### The Reality

Image

### Your Proposal

/

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Roelof033**
Fixes GTNewHorizons/GT-New-Horizons-Modpack#23301

**What's broken?**
When using the Backhand mod, the Draconic Chestplate's left arm stays stuck at the side instead of raising up to hold the item. It looks weird when you're holding a item the offhand.

**What I fixed**
I updated `ModelDraconicArmor.java` to check if the player is holding an offhand item. If they are, I apply the standard vanilla rotation to the left arm so it looks correct.

**Crash Protection:**
I wrapped the fix in a static helper class and added a `Loader.isModLoaded("backhand")` check. This acts as a soft dependency if someone plays this without Backhand installed, the game will still run perfectly fine without crashing.

### Screenshots
**Before (Arm stuck at side):**
![Before Fix]before

**After (Arm holding item):**
![After Fix]
after

P.S. This is my first pull request. I would appreciate any feedback on my code style or formatting.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Roelof033 not building
* What went wrong:
```Execution failed for task ':compileJava'.
> Compilation failed; see the compiler output below.
  /home/runner/work/Draconic-Evolution/Draconic-Evolution/src/main/java/com/brandon3055/draconicevolution/client/model/ModelDraconicArmor.java:220: error: package xonin.backhand.api.core does not exist
              if (xonin.backhand.api.core.BackhandUtils.getOffhandItem(player) != null) {
                                         ^
  1 error```

**Review by Ruling-0 — DISMISSED** [review]

File: src/main/java/com/brandon3055/draconicevolution/client/model/ModelDraconicArmor.java [hunk 1]
```diff
@@ -173,7 +174,14 @@ public void render(Entity entity, float f, float f1, float f2, float f3, float f
             bipedRightLeg.rotateAngleZ = 0F;
 
             setRotationAngles(0, 0, 0, 0, 0, 0, null);
-        } else super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
+        } else {
+            super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
+            if (entity instanceof EntityPlayer) {
+                if (cpw.mods.fml.common.Loader.isModLoaded("backhand")) {
```
Comment (Ruling-0) [inline src/main/java/com/brandon3055/draconicevolution/client/model/ModelDraconicArmor.java]: `isModLoaded()` is a pretty slow call (especially for a render call), and doesn't change during runtime, so you want to cache it into some static variable. For consistency, I'd do it in integration/ModHelper (see `isGTNHlibLoaded`), then replace this check with `ModHelper.isBackhandLoaded`.

File: src/main/java/com/brandon3055/draconicevolution/client/model/ModelDraconicArmor.java [hunk 2]
```diff
@@ -205,4 +213,14 @@ public void setRotationAngles(float p_78087_1_, float p_78087_2_, float p_78087_
         this.bipedRightArm.rotateAngleZ = 0.0F;
         this.bipedLeftArm.rotateAngleZ = 0.0F;
     }
+
+    private static class BackhandHelper {
+
+        public static void applyFix(ModelDraconicArmor model, EntityPlayer player) {
+            if (xonin.backhand.api.core.BackhandUtils.getOffhandItem(player) != null) {
```
Comment (Ruling-0) [inline src/main/java/com/brandon3055/draconicevolution/client/model/ModelDraconicArmor.java]: Code-style wise, this should just be `BackhandUtils.getOffhandItem` and leave the rest of the package name to an import statement.

**Review by Ruling-0 — CHANGES_REQUESTED** [review]
Thanks for your PR! It's pretty good, just need a couple of things addressed.

**Comment by Dream-Master** [comment]
@Roelof033

**Review by Ruling-0 — APPROVED** [review]

**Comment by Dream-Master** [comment]
Spotless
